# DQN Configuration for CartPole-v1
algorithm: dqn
environment:
  name: CartPole-v1
  render_mode: null

network:
  hidden_layers: [64, 64]
  activation: relu

training:
  learning_rate: 0.001
  batch_size: 32
  memory_size: 10000
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  target_update: 1000
  gamma: 0.99
  learning_starts: 1000
  timesteps: 100000
  save_frequency: 10000
  eval_frequency: 5000
  eval_episodes: 10

logging:
  log_dir: ./logs
  tensorboard: true
  wandb: false